/* arena.js — 4 minijuegos (récord personal en localStorage). No usa Riot API. */
let mode="aim",running=false,raf=null,tickTimer=null,spawnTimer=null;
let score=0,misses=0,timeLeft=30,champPool=[];
const $=id=>document.getElementById(id);const arena=()=>$("arena");
const MODES={aim:{label:"🎯 Puntería",unit:"pts",lower:false},dodge:{label:"💨 Esquiva",unit:"s",lower:false,div:1000,dec:1},dodgeshoot:{label:"🔫 Esquiva y dispara",unit:"pts",lower:false},reaction:{label:"⚡ Reacción",unit:"ms",lower:true}};
function fmt(m,v){const M=MODES[m];if(M.div)return (v/M.div).toFixed(M.dec||0);return String(v);}
function bestKey(m){return "lh:arena:best:"+m;}
function getBest(m){const v=localStorage.getItem(bestKey(m));return v==null?null:+v;}
function setBest(m,v){const b=getBest(m);const better=b==null||(MODES[m].lower?v<b:v>b);if(better){localStorage.setItem(bestKey(m),v);return true;}return false;}
function showBest(){const b=getBest(mode);$("ar-best").textContent=b!=null?`🏆 Tu récord: ${fmt(mode,b)} ${MODES[mode].unit}`:"Sin marca aún";}
function resetHud(){score=0;misses=0;$("ar-score").textContent="0";if(mode==="reaction"){$("ar-time").textContent="—";$("ar-extra-lbl").textContent="Ronda";$("ar-extra").textContent="0/5";}else if(mode==="aim"){$("ar-time").textContent="30";$("ar-extra-lbl").textContent="Precisión";$("ar-extra").textContent="100%";}else if(mode==="dodge"){$("ar-time").textContent="0.0";$("ar-extra-lbl").textContent="Esquivadas";$("ar-extra").textContent="0";}else{$("ar-time").textContent="0.0";$("ar-extra-lbl").textContent="Enemigos";$("ar-extra").textContent="0";}}
function showOverlay(v){$("ar-overlay").style.display=v?"flex":"none";}
function setMode(m){if(running)stop();mode=m;document.querySelectorAll(".ar-modes .rk-tab").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));const inner=$("ar-ov-inner");const desc={aim:"Clica los campeones lo más rápido que puedas antes de que desaparezcan. ¡30 segundos!",dodge:"Mueve el ratón esquivando las habilidades. Aguanta lo máximo sin que te toquen.",dodgeshoot:"Esquiva los skillshots MORADOS Y clica los enemigos ROJOS para dispararles. ¡A la vez!",reaction:"Espera a que la arena se ponga VERDE y clica lo más rápido posible. 5 rondas."}[m];inner.innerHTML=`<div class="ar-ov-title">${MODES[m].label}</div><div class="ar-ov-desc">${desc}</div><button class="btn primary" id="ar-play">▶ Jugar</button>`;$("ar-play").addEventListener("click",start);const a=arena();a.className="ar-arena";a.innerHTML="";a.appendChild($("ar-overlay"));resetHud();showOverlay(true);showBest();}
/* PUNTERÍA */
function startAim(){running=true;score=0;misses=0;timeLeft=30;resetHud();showOverlay(false);const a=arena();a.querySelectorAll(".ar-target").forEach(t=>t.remove());a.classList.add("aim-mode");a._miss=e=>{if(e.target.closest(".ar-target"))return;misses++;updateAcc();};a.addEventListener("pointerdown",a._miss);tickTimer=setInterval(()=>{timeLeft-=0.1;if(timeLeft<=0){$("ar-time").textContent="0.0";endAim();return;}$("ar-time").textContent=timeLeft.toFixed(1);},100);scheduleSpawn();}
function scheduleSpawn(){if(!running)return;spawnChamp();spawnTimer=setTimeout(scheduleSpawn,Math.max(360,820-(30-timeLeft)*14));}
function spawnChamp(){const a=arena();const rect=a.getBoundingClientRect();const size=Math.max(44,Math.min(72,rect.width/12));const x=Math.random()*(rect.width-size),y=Math.random()*(rect.height-size);const c=champPool[Math.floor(Math.random()*champPool.length)];const t=document.createElement("div");t.className="ar-target spawn";t.style.cssText=`left:${x}px;top:${y}px;width:${size}px;height:${size}px`;t.innerHTML=`<img src="${champIcon(c.id)}" draggable="false">`;const life=setTimeout(()=>{t.classList.add("gone");setTimeout(()=>t.remove(),150);},Math.max(700,1200-(30-timeLeft)*18));t.addEventListener("pointerdown",e=>{e.stopPropagation();clearTimeout(life);score++;$("ar-score").textContent=score;updateAcc();t.classList.add("hit");setTimeout(()=>t.remove(),150);});a.appendChild(t);}
function updateAcc(){const total=score+misses;$("ar-extra").textContent=(total?Math.round(score/total*100):100)+"%";}
function endAim(){running=false;clearInterval(tickTimer);clearTimeout(spawnTimer);const a=arena();a.removeEventListener("pointerdown",a._miss);a.querySelectorAll(".ar-target").forEach(t=>t.remove());const acc=(score+misses)?Math.round(score/(score+misses)*100):100;finish(score,`⏱️ ¡Tiempo!`,`Has acertado <b>${score}</b> campeones con <b>${acc}%</b> de precisión.`);}
/* ESQUIVA / ESQUIVA Y DISPARA (canvas) */
let cv=null,ctx=null,W=0,H=0,mouse={x:0,y:0,in:false},shots=[],enemies=[],dodged=0,elapsed=0,spawnAcc=0,enemyAcc=0,lastT=0;
function ensureCanvas(){if(cv&&cv.parentElement===arena())return;cv=document.createElement("canvas");cv.className="ar-canvas";arena().appendChild(cv);ctx=cv.getContext("2d");const move=e=>{const r=cv.getBoundingClientRect();const cx=(e.touches?e.touches[0].clientX:e.clientX),cy=(e.touches?e.touches[0].clientY:e.clientY);mouse.x=cx-r.left;mouse.y=cy-r.top;mouse.in=true;};cv.addEventListener("pointermove",move);cv.addEventListener("touchmove",e=>{move(e);e.preventDefault();},{passive:false});cv.addEventListener("pointerleave",()=>mouse.in=false);cv.addEventListener("pointerdown",e=>{if(mode!=="dodgeshoot"||!running)return;const r=cv.getBoundingClientRect();const mx=e.clientX-r.left,my=e.clientY-r.top;for(let i=enemies.length-1;i>=0;i--){const en=enemies[i];const dx=en.x-mx,dy=en.y-my;if(dx*dx+dy*dy<(en.r+6)*(en.r+6)){enemies.splice(i,1);score++;$("ar-score").textContent=score;$("ar-extra").textContent=score;break;}}});}
function resizeCanvas(){const r=arena().getBoundingClientRect();W=cv.width=r.width;H=cv.height=r.height;}
function startDodge(){arena().querySelectorAll(".ar-canvas").forEach(c=>c.remove());cv=null;ensureCanvas();resizeCanvas();running=true;shots=[];enemies=[];dodged=0;score=0;elapsed=0;spawnAcc=0;enemyAcc=0;lastT=performance.now();mouse.x=W/2;mouse.y=H/2;resetHud();showOverlay(false);arena().classList.add(mode==="dodgeshoot"?"shoot-mode":"dodge-mode");raf=requestAnimationFrame(dodgeLoop);}
function spawnShot(){const side=Math.floor(Math.random()*4);let x,y;if(side===0){x=Math.random()*W;y=-20;}else if(side===1){x=W+20;y=Math.random()*H;}else if(side===2){x=Math.random()*W;y=H+20;}else{x=-20;y=Math.random()*H;}const tx=mouse.x+(Math.random()-0.5)*120,ty=mouse.y+(Math.random()-0.5)*120;const ang=Math.atan2(ty-y,tx-x);const speed=2.6+Math.min(4,elapsed/8);const r=9+Math.random()*7;shots.push({x,y,vx:Math.cos(ang)*speed,vy:Math.sin(ang)*speed,r,counted:false});}
function spawnEnemy(){const r=16;const x=r+Math.random()*(W-2*r),y=r+Math.random()*(H-2*r);const c=champPool[Math.floor(Math.random()*champPool.length)];const img=new Image();img.src=champIcon(c.id);enemies.push({x,y,r,img});}
function dodgeLoop(t){if(!running)return;const dt=Math.min(50,t-lastT);lastT=t;elapsed+=dt/1000;$("ar-time").textContent=elapsed.toFixed(1);spawnAcc+=dt;if(spawnAcc>=Math.max(180,620-elapsed*22)){spawnAcc=0;spawnShot();}if(mode==="dodgeshoot"){enemyAcc+=dt;if(enemyAcc>=1400){enemyAcc=0;if(enemies.length<5)spawnEnemy();}}ctx.clearRect(0,0,W,H);enemies.forEach(en=>{ctx.save();ctx.beginPath();ctx.arc(en.x,en.y,en.r+3,0,7);ctx.strokeStyle="rgba(255,96,96,.9)";ctx.lineWidth=3;ctx.shadowBlur=12;ctx.shadowColor="rgba(255,96,96,.8)";ctx.stroke();ctx.closePath();ctx.beginPath();ctx.arc(en.x,en.y,en.r,0,7);ctx.clip();try{ctx.drawImage(en.img,en.x-en.r,en.y-en.r,en.r*2,en.r*2);}catch(e){}ctx.restore();});if(mouse.in){ctx.beginPath();ctx.arc(mouse.x,mouse.y,13,0,7);ctx.fillStyle="rgba(200,170,110,.9)";ctx.shadowBlur=18;ctx.shadowColor="rgba(200,170,110,.9)";ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(mouse.x,mouse.y,7,0,7);ctx.fillStyle="#fff";ctx.fill();}for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.x+=s.vx;s.y+=s.vy;if(s.x<-40||s.x>W+40||s.y<-40||s.y>H+40){if(!s.counted){dodged++;if(mode==="dodge")$("ar-extra").textContent=dodged;}shots.splice(i,1);continue;}if(mouse.in){const dx=s.x-mouse.x,dy=s.y-mouse.y;if(dx*dx+dy*dy<(s.r+11)*(s.r+11)){endDodge();return;}}ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fillStyle="rgba(200,120,255,.95)";ctx.shadowBlur=14;ctx.shadowColor="rgba(200,120,255,.9)";ctx.fill();ctx.shadowBlur=0;}raf=requestAnimationFrame(dodgeLoop);}
function endDodge(){running=false;cancelAnimationFrame(raf);if(mode==="dodge"){finish(Math.round(elapsed*1000),`💥 ¡Tocado!`,`Aguantaste <b>${elapsed.toFixed(1)} s</b> y esquivaste <b>${dodged}</b> habilidades.`);}else{finish(score,`💥 ¡Tocado!`,`Aguantaste <b>${elapsed.toFixed(1)} s</b> y disparaste a <b>${score}</b> enemigos.`);}setTimeout(()=>{if(ctx)ctx.clearRect(0,0,W,H);},50);}
/* REACCIÓN */
let rxRound=0,rxTimes=[],rxState="idle",rxStart=0,rxTimeout=null;
function startReaction(){running=true;rxRound=0;rxTimes=[];resetHud();showOverlay(false);const a=arena();a.classList.add("rx-mode");a.innerHTML=`<div class="rx-box waiting" id="rx-box"><div class="rx-msg" id="rx-msg">Prepárate…</div></div>`;const box=$("rx-box");box.addEventListener("pointerdown",()=>{if(rxState==="wait"){clearTimeout(rxTimeout);box.className="rx-box early";$("rx-msg").textContent="¡Demasiado pronto! 😅 Espera al verde…";rxState="idle";setTimeout(nextRound,900);}else if(rxState==="go"){const ms=Math.round(performance.now()-rxStart);rxTimes.push(ms);rxRound++;box.className="rx-box hit";$("rx-msg").textContent=`${ms} ms`;$("ar-extra").textContent=`${rxRound}/5`;if(rxRound>=5){setTimeout(endReaction,700);}else{rxState="idle";setTimeout(nextRound,700);}}});nextRound();}
function nextRound(){if(!running)return;const box=$("rx-box");if(!box)return;box.className="rx-box waiting";$("rx-msg").textContent=`Ronda ${rxRound+1}/5 · espera al VERDE…`;rxState="wait";rxTimeout=setTimeout(()=>{box.className="rx-box go";$("rx-msg").textContent="¡YA! 🟢";rxState="go";rxStart=performance.now();},900+Math.random()*2600);}
function endReaction(){running=false;const avg=Math.round(rxTimes.reduce((a,b)=>a+b,0)/rxTimes.length);const best=Math.min(...rxTimes);finish(avg,`⚡ ¡Terminado!`,`Media: <b>${avg} ms</b> · mejor ronda: <b>${best} ms</b><br><small>${rxTimes.join(" · ")} ms</small>`);}
/* fin */
function finish(value,title,html){const isRec=setBest(mode,value);showBest();const inner=$("ar-ov-inner");inner.innerHTML=`<div class="ar-ov-title">${title}</div><div class="ar-ov-desc">${html}${isRec?"<br>🏆 <b>¡Nuevo récord personal!</b>":""}</div><button class="btn primary" id="ar-play">🔁 Otra vez</button>`;$("ar-play").addEventListener("click",start);showOverlay(true);}
function start(){const a=arena();a.querySelectorAll(".ar-target").forEach(t=>t.remove());if(mode==="aim")startAim();else if(mode==="reaction")startReaction();else startDodge();}
function stop(){running=false;clearInterval(tickTimer);clearTimeout(spawnTimer);clearTimeout(rxTimeout);if(raf)cancelAnimationFrame(raf);const a=arena();if(a._miss)a.removeEventListener("pointerdown",a._miss);if(ctx)ctx.clearRect(0,0,W,H);}
(async function(){injectNav("arena.html");initFX();await loadDDragon();champPool=CHAMPIONS.length?CHAMPIONS:[{id:"Poro"}];document.querySelectorAll(".ar-modes .rk-tab").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));$("ar-start").addEventListener("click",start);window.addEventListener("resize",()=>{if(cv&&(mode==="dodge"||mode==="dodgeshoot")&&!running)resizeCanvas();});setMode("aim");})();
