/* =====================================================================
   loldle-data.js — Datos CURADOS de campeones para el LoLdle
   ---------------------------------------------------------------------
   Riot Data Dragon NO expone especie, región ni año de lanzamiento,
   así que van a mano aquí. Si ves algún dato mal, corrígelo en su línea.
     sp = especie   ·   rg = región(es)   ·   yr = año de lanzamiento
   ===================================================================== */
const CHAMP_META = {
Aatrox:{sp:"Darkin",rg:["Runeterra"],yr:2013},
Ahri:{sp:"Vastaya",rg:["Jonia"],yr:2011},
Akali:{sp:"Humano",rg:["Jonia"],yr:2010},
Akshan:{sp:"Humano",rg:["Shurima"],yr:2021},
Alistar:{sp:"Minotauro",rg:["Runeterra"],yr:2009},
Ambessa:{sp:"Humano",rg:["Noxus"],yr:2024},
Amumu:{sp:"No-muerto",rg:["Shurima"],yr:2009},
Anivia:{sp:"Semidiós",rg:["Freljord"],yr:2009},
Annie:{sp:"Humano",rg:["Runeterra"],yr:2009},
Aphelios:{sp:"Humano",rg:["Targon"],yr:2019},
Ashe:{sp:"Humano",rg:["Freljord"],yr:2009},
AurelionSol:{sp:"Celestial",rg:["Runeterra"],yr:2016},
Aurora:{sp:"Vastaya",rg:["Freljord"],yr:2024},
Azir:{sp:"No-muerto",rg:["Shurima"],yr:2014},
Bard:{sp:"Celestial",rg:["Runeterra"],yr:2015},
Belveth:{sp:"Vacío",rg:["Vacío"],yr:2022},
Blitzcrank:{sp:"Máquina",rg:["Zaun"],yr:2009},
Brand:{sp:"Demonio",rg:["Runeterra"],yr:2011},
Braum:{sp:"Humano",rg:["Freljord"],yr:2014},
Briar:{sp:"Demonio",rg:["Noxus"],yr:2023},
Caitlyn:{sp:"Humano",rg:["Piltover"],yr:2011},
Camille:{sp:"Humano",rg:["Piltover"],yr:2016},
Cassiopeia:{sp:"Humano",rg:["Noxus"],yr:2011},
Chogath:{sp:"Vacío",rg:["Vacío"],yr:2009},
Corki:{sp:"Yordle",rg:["Bandópolis"],yr:2009},
Darius:{sp:"Humano",rg:["Noxus"],yr:2012},
Diana:{sp:"Aspecto",rg:["Targon"],yr:2012},
DrMundo:{sp:"Humano",rg:["Zaun"],yr:2009},
Draven:{sp:"Humano",rg:["Noxus"],yr:2012},
Ekko:{sp:"Humano",rg:["Zaun"],yr:2015},
Elise:{sp:"Humano",rg:["Islas de la Sombra"],yr:2012},
Evelynn:{sp:"Demonio",rg:["Runeterra"],yr:2009},
Ezreal:{sp:"Humano",rg:["Piltover"],yr:2010},
Fiddlesticks:{sp:"Demonio",rg:["Runeterra"],yr:2009},
Fiora:{sp:"Humano",rg:["Demacia"],yr:2012},
Fizz:{sp:"Anfibio",rg:["Bilgewater"],yr:2011},
Galio:{sp:"Golem",rg:["Demacia"],yr:2010},
Gangplank:{sp:"Humano",rg:["Bilgewater"],yr:2009},
Garen:{sp:"Humano",rg:["Demacia"],yr:2010},
Gnar:{sp:"Yordle",rg:["Freljord"],yr:2014},
Gragas:{sp:"Humano",rg:["Freljord"],yr:2010},
Graves:{sp:"Humano",rg:["Bilgewater"],yr:2011},
Gwen:{sp:"Espíritu",rg:["Islas de la Sombra"],yr:2021},
Hecarim:{sp:"No-muerto",rg:["Islas de la Sombra"],yr:2012},
Heimerdinger:{sp:"Yordle",rg:["Piltover"],yr:2009},
Hwei:{sp:"Humano",rg:["Jonia"],yr:2023},
Illaoi:{sp:"Humano",rg:["Bilgewater"],yr:2015},
Irelia:{sp:"Humano",rg:["Jonia"],yr:2010},
Ivern:{sp:"Espíritu",rg:["Freljord"],yr:2016},
Janna:{sp:"Espíritu",rg:["Zaun"],yr:2009},
JarvanIV:{sp:"Humano",rg:["Demacia"],yr:2011},
Jax:{sp:"Otro",rg:["Runeterra"],yr:2009},
Jayce:{sp:"Humano",rg:["Piltover"],yr:2012},
Jhin:{sp:"Humano",rg:["Jonia"],yr:2016},
Jinx:{sp:"Humano",rg:["Zaun"],yr:2013},
Kaisa:{sp:"Humano",rg:["Vacío"],yr:2018},
Kalista:{sp:"No-muerto",rg:["Islas de la Sombra"],yr:2014},
Karma:{sp:"Humano",rg:["Jonia"],yr:2011},
Karthus:{sp:"No-muerto",rg:["Islas de la Sombra"],yr:2009},
Kassadin:{sp:"Humano",rg:["Vacío"],yr:2009},
Katarina:{sp:"Humano",rg:["Noxus"],yr:2009},
Kayle:{sp:"Aspecto",rg:["Demacia"],yr:2009},
Kayn:{sp:"Humano",rg:["Jonia"],yr:2017},
Kennen:{sp:"Yordle",rg:["Jonia"],yr:2010},
Khazix:{sp:"Vacío",rg:["Vacío"],yr:2012},
Kindred:{sp:"Espíritu",rg:["Runeterra"],yr:2015},
Kled:{sp:"Yordle",rg:["Noxus"],yr:2016},
KogMaw:{sp:"Vacío",rg:["Vacío"],yr:2010},
Ksante:{sp:"Humano",rg:["Shurima"],yr:2022},
Leblanc:{sp:"Humano",rg:["Noxus"],yr:2010},
LeeSin:{sp:"Humano",rg:["Jonia"],yr:2011},
Leona:{sp:"Aspecto",rg:["Targon"],yr:2011},
Lillia:{sp:"Espíritu",rg:["Jonia"],yr:2020},
Lissandra:{sp:"Humano",rg:["Freljord"],yr:2013},
Lucian:{sp:"Humano",rg:["Islas de la Sombra"],yr:2013},
Lulu:{sp:"Yordle",rg:["Bandópolis"],yr:2012},
Lux:{sp:"Humano",rg:["Demacia"],yr:2010},
Malphite:{sp:"Golem",rg:["Ixtal"],yr:2009},
Malzahar:{sp:"Humano",rg:["Vacío"],yr:2010},
Maokai:{sp:"Espíritu",rg:["Islas de la Sombra"],yr:2011},
MasterYi:{sp:"Humano",rg:["Jonia"],yr:2009},
Mel:{sp:"Humano",rg:["Noxus"],yr:2025},
Milio:{sp:"Humano",rg:["Ixtal"],yr:2023},
MissFortune:{sp:"Humano",rg:["Bilgewater"],yr:2010},
MonkeyKing:{sp:"Vastaya",rg:["Jonia"],yr:2011},
Mordekaiser:{sp:"No-muerto",rg:["Noxus"],yr:2010},
Morgana:{sp:"Aspecto",rg:["Demacia"],yr:2009},
Naafiri:{sp:"Darkin",rg:["Shurima"],yr:2023},
Nami:{sp:"Vastaya",rg:["Bilgewater"],yr:2012},
Nasus:{sp:"Semidiós",rg:["Shurima"],yr:2009},
Nautilus:{sp:"No-muerto",rg:["Bilgewater"],yr:2012},
Neeko:{sp:"Vastaya",rg:["Ixtal"],yr:2018},
Nidalee:{sp:"Humano",rg:["Ixtal"],yr:2009},
Nilah:{sp:"Humano",rg:["Bilgewater"],yr:2022},
Nocturne:{sp:"Demonio",rg:["Runeterra"],yr:2011},
Nunu:{sp:"Humano",rg:["Freljord"],yr:2009},
Olaf:{sp:"Humano",rg:["Freljord"],yr:2010},
Orianna:{sp:"Máquina",rg:["Piltover"],yr:2011},
Ornn:{sp:"Dios",rg:["Freljord"],yr:2017},
Pantheon:{sp:"Aspecto",rg:["Targon"],yr:2010},
Poppy:{sp:"Yordle",rg:["Demacia"],yr:2010},
Pyke:{sp:"No-muerto",rg:["Bilgewater"],yr:2018},
Qiyana:{sp:"Humano",rg:["Ixtal"],yr:2019},
Quinn:{sp:"Humano",rg:["Demacia"],yr:2013},
Rakan:{sp:"Vastaya",rg:["Jonia"],yr:2017},
Rammus:{sp:"Bestia",rg:["Shurima"],yr:2009},
RekSai:{sp:"Vacío",rg:["Vacío"],yr:2014},
Rell:{sp:"Humano",rg:["Noxus"],yr:2020},
Renata:{sp:"Humano",rg:["Zaun"],yr:2022},
Renekton:{sp:"Semidiós",rg:["Shurima"],yr:2011},
Rengar:{sp:"Vastaya",rg:["Ixtal"],yr:2012},
Riven:{sp:"Humano",rg:["Noxus"],yr:2011},
Rumble:{sp:"Yordle",rg:["Bandópolis"],yr:2011},
Ryze:{sp:"Humano",rg:["Runeterra"],yr:2009},
Samira:{sp:"Humano",rg:["Noxus"],yr:2020},
Sejuani:{sp:"Humano",rg:["Freljord"],yr:2012},
Senna:{sp:"Humano",rg:["Islas de la Sombra"],yr:2019},
Seraphine:{sp:"Humano",rg:["Piltover"],yr:2020},
Sett:{sp:"Vastaya",rg:["Jonia"],yr:2020},
Shaco:{sp:"Demonio",rg:["Runeterra"],yr:2009},
Shen:{sp:"Humano",rg:["Jonia"],yr:2010},
Shyvana:{sp:"Dragón",rg:["Demacia"],yr:2011},
Singed:{sp:"Humano",rg:["Zaun"],yr:2009},
Sion:{sp:"No-muerto",rg:["Noxus"],yr:2009},
Sivir:{sp:"Humano",rg:["Shurima"],yr:2009},
Skarner:{sp:"Brackern",rg:["Shurima"],yr:2011},
Smolder:{sp:"Dragón",rg:["Camavor"],yr:2024},
Sona:{sp:"Humano",rg:["Demacia"],yr:2010},
Soraka:{sp:"Celestial",rg:["Targon"],yr:2009},
Swain:{sp:"Humano",rg:["Noxus"],yr:2010},
Sylas:{sp:"Humano",rg:["Demacia"],yr:2019},
Syndra:{sp:"Humano",rg:["Jonia"],yr:2012},
TahmKench:{sp:"Demonio",rg:["Bilgewater"],yr:2015},
Taliyah:{sp:"Humano",rg:["Shurima"],yr:2016},
Talon:{sp:"Humano",rg:["Noxus"],yr:2011},
Taric:{sp:"Aspecto",rg:["Targon"],yr:2009},
Teemo:{sp:"Yordle",rg:["Bandópolis"],yr:2009},
Thresh:{sp:"No-muerto",rg:["Islas de la Sombra"],yr:2013},
Tristana:{sp:"Yordle",rg:["Bandópolis"],yr:2009},
Trundle:{sp:"Troll",rg:["Freljord"],yr:2010},
Tryndamere:{sp:"Humano",rg:["Freljord"],yr:2009},
TwistedFate:{sp:"Humano",rg:["Bilgewater"],yr:2009},
Twitch:{sp:"Bestia",rg:["Zaun"],yr:2009},
Udyr:{sp:"Humano",rg:["Freljord"],yr:2009},
Urgot:{sp:"Humano",rg:["Zaun"],yr:2010},
Varus:{sp:"Darkin",rg:["Jonia"],yr:2012},
Vayne:{sp:"Humano",rg:["Demacia"],yr:2011},
Veigar:{sp:"Yordle",rg:["Bandópolis"],yr:2009},
Velkoz:{sp:"Vacío",rg:["Vacío"],yr:2014},
Vex:{sp:"Yordle",rg:["Islas de la Sombra"],yr:2021},
Vi:{sp:"Humano",rg:["Piltover"],yr:2012},
Viego:{sp:"No-muerto",rg:["Islas de la Sombra"],yr:2021},
Viktor:{sp:"Humano",rg:["Zaun"],yr:2011},
Vladimir:{sp:"Humano",rg:["Noxus"],yr:2010},
Volibear:{sp:"Dios",rg:["Freljord"],yr:2011},
Warwick:{sp:"Bestia",rg:["Zaun"],yr:2009},
Xayah:{sp:"Vastaya",rg:["Jonia"],yr:2017},
Xerath:{sp:"Ascendido",rg:["Shurima"],yr:2011},
XinZhao:{sp:"Humano",rg:["Demacia"],yr:2010},
Yasuo:{sp:"Humano",rg:["Jonia"],yr:2013},
Yone:{sp:"No-muerto",rg:["Jonia"],yr:2020},
Yorick:{sp:"No-muerto",rg:["Islas de la Sombra"],yr:2011},
Yunara:{sp:"Humano",rg:["Jonia"],yr:2025},
Yuumi:{sp:"Gato mágico",rg:["Bandópolis"],yr:2019},
Zac:{sp:"Otro",rg:["Zaun"],yr:2013},
Zed:{sp:"Humano",rg:["Jonia"],yr:2012},
Zeri:{sp:"Humano",rg:["Zaun"],yr:2022},
Ziggs:{sp:"Yordle",rg:["Bandópolis"],yr:2012},
Zilean:{sp:"Humano",rg:["Runeterra"],yr:2009},
Zoe:{sp:"Aspecto",rg:["Targon"],yr:2017},
Zyra:{sp:"Planta",rg:["Ixtal"],yr:2012}
};
/* Fallback por si sale un campeón nuevo que no esté en la lista */
const META_DEFAULT={sp:"Humano",rg:["Runeterra"],yr:2025};
function metaOf(id){return CHAMP_META[id]||META_DEFAULT;}

/* Posiciones (las mismas que usa la página de Campeones) */
const LD_LANES={Aatrox:["Top"],Ahri:["Medio"],Akali:["Medio","Top"],Akshan:["Medio","Top"],Alistar:["Support"],Ambessa:["Top","Medio"],Amumu:["Jungla","Support"],Anivia:["Medio"],Annie:["Medio","Support"],Aphelios:["ADC"],Ashe:["ADC","Support"],AurelionSol:["Medio"],Aurora:["Medio","Top"],Azir:["Medio"],Bard:["Support"],Belveth:["Jungla"],Blitzcrank:["Support"],Brand:["Support","Medio"],Braum:["Support"],Briar:["Jungla"],Caitlyn:["ADC"],Camille:["Top"],Cassiopeia:["Medio"],Chogath:["Top","Medio"],Corki:["Medio","ADC"],Darius:["Top"],Diana:["Jungla","Medio"],DrMundo:["Top"],Draven:["ADC"],Ekko:["Jungla","Medio"],Elise:["Jungla"],Evelynn:["Jungla"],Ezreal:["ADC"],Fiddlesticks:["Jungla"],Fiora:["Top"],Fizz:["Medio"],Galio:["Medio","Support"],Gangplank:["Top"],Garen:["Top"],Gnar:["Top"],Gragas:["Jungla","Top"],Graves:["Jungla"],Gwen:["Top","Jungla"],Hecarim:["Jungla"],Heimerdinger:["Medio","Support"],Hwei:["Medio","Support"],Illaoi:["Top"],Irelia:["Top","Medio"],Ivern:["Jungla"],Janna:["Support"],JarvanIV:["Jungla"],Jax:["Top","Jungla"],Jayce:["Top","Medio"],Jhin:["ADC"],Jinx:["ADC"],Ksante:["Top"],Kaisa:["ADC"],Kalista:["ADC"],Karma:["Support","Medio"],Karthus:["Jungla"],Kassadin:["Medio"],Katarina:["Medio"],Kayle:["Top"],Kayn:["Jungla"],Kennen:["Top"],Khazix:["Jungla"],Kindred:["Jungla"],Kled:["Top"],KogMaw:["ADC"],Leblanc:["Medio"],LeeSin:["Jungla"],Leona:["Support"],Lillia:["Jungla"],Lissandra:["Medio"],Lucian:["ADC","Medio"],Lulu:["Support"],Lux:["Support","Medio"],Malphite:["Top","Support"],Malzahar:["Medio"],Maokai:["Support","Top","Jungla"],MasterYi:["Jungla"],Mel:["Medio"],Milio:["Support"],MissFortune:["ADC","Support"],MonkeyKing:["Top","Jungla"],Mordekaiser:["Top"],Morgana:["Support","Medio"],Naafiri:["Medio","Jungla"],Nami:["Support"],Nasus:["Top"],Nautilus:["Support"],Neeko:["Medio","Support"],Nidalee:["Jungla"],Nilah:["ADC"],Nocturne:["Jungla"],Nunu:["Jungla"],Olaf:["Jungla","Top"],Orianna:["Medio"],Ornn:["Top"],Pantheon:["Support","Top","Medio"],Poppy:["Top","Jungla","Support"],Pyke:["Support"],Qiyana:["Medio"],Quinn:["Top"],Rakan:["Support"],Rammus:["Jungla"],RekSai:["Jungla"],Rell:["Support"],Renata:["Support"],Renekton:["Top"],Rengar:["Jungla","Top"],Riven:["Top"],Rumble:["Top","Medio"],Ryze:["Medio","Top"],Samira:["ADC"],Sejuani:["Jungla"],Senna:["Support","ADC"],Seraphine:["Support","Medio","ADC"],Sett:["Top","Support"],Shaco:["Jungla","Support"],Shen:["Top","Support"],Shyvana:["Jungla"],Singed:["Top"],Sion:["Top"],Sivir:["ADC"],Skarner:["Jungla"],Smolder:["ADC"],Sona:["Support"],Soraka:["Support"],Swain:["Medio","Support","ADC"],Sylas:["Medio"],Syndra:["Medio"],TahmKench:["Support","Top"],Taliyah:["Jungla","Medio"],Talon:["Medio","Jungla"],Taric:["Support"],Teemo:["Top"],Thresh:["Support"],Tristana:["ADC","Medio"],Trundle:["Jungla","Top"],Tryndamere:["Top"],TwistedFate:["Medio"],Twitch:["ADC"],Udyr:["Jungla"],Urgot:["Top"],Varus:["ADC"],Vayne:["ADC","Top"],Veigar:["Medio","Support"],Velkoz:["Support","Medio"],Vex:["Medio"],Vi:["Jungla"],Viego:["Jungla"],Viktor:["Medio"],Vladimir:["Medio","Top"],Volibear:["Jungla","Top"],Warwick:["Jungla","Top"],Xayah:["ADC"],Xerath:["Medio","Support"],XinZhao:["Jungla"],Yasuo:["Medio","Top"],Yone:["Medio","Top"],Yorick:["Top"],Yunara:["ADC"],Yuumi:["Support"],Zac:["Jungla"],Zed:["Medio","Jungla"],Zeri:["ADC"],Ziggs:["Medio","ADC"],Zilean:["Support","Medio"],Zoe:["Medio"],Zyra:["Support"]};
function lanesOf(c){if(LD_LANES[c.id])return LD_LANES[c.id];const t=c.tags||[];
  if(t.includes("Marksman"))return["ADC"];if(t.includes("Support"))return["Support"];
  if(t.includes("Assassin")||t.includes("Mage"))return["Medio"];if(t.includes("Tank"))return["Top","Support"];
  if(t.includes("Fighter"))return["Top","Jungla"];return["Medio"];}
